# Generated by Django 4.1.7 on 2023-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costumer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="costumer",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="costumer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
