# Generated by Django 4.1.7 on 2023-03-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_costumer_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costumer",
            name="created",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="costumer",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
