# Generated by Django 4.1.7 on 2023-03-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
