# Generated by Django 4.1.7 on 2023-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_costumer_created_costumer_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costumer",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
