# Generated by Django 4.1.7 on 2023-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nom',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
