# Generated by Django 4.1.7 on 2023-04-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nom',
        ),
    ]
