# Generated by Django 4.1.7 on 2023-04-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customer_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Gerant'), (2, 'Staff'), (3, 'Client')], default=3, null=True),
        ),
    ]
