# Generated by Django 4.2 on 2023-04-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedproduct',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='archivedproduct',
            name='image_list',
        ),
        migrations.RemoveField(
            model_name='archivedproduct',
            name='ratings',
        ),
    ]
