# Generated by Django 4.2 on 2023-04-27 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_archivedproduct_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedproduct',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000000.0), django.core.validators.MinValueValidator(0)]),
        ),
    ]
